### PR TITLE
Laravel 10 Support

### PR DESCRIPTION
**Pull request by lrljoe**

### CODE REVIEW

**Comment by ajayfroiden** [comment]
@lrljoe Please approve this

**Comment by lrljoe** [comment]
> @lrljoe Please approve this

It's for @tanmuhittin to approve I'm afraid, I just created the PR to fix it!

**Comment by ajayfroiden** [comment]
@lrljoe Sorry it was meant for @tanmuhittin

**Comment by tanmuhittin** [comment]
Thanks for the contribution

**Pull request merged**
